# Generated by Django 3.0.8 on 2020-07-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data', models.DateField(auto_now_add=True)),
                ('materia', models.CharField(max_length=15)),
                ('link', models.CharField(max_length=1000)),
                ('thumb', models.ImageField(upload_to='')),
            ],
        ),
    ]
