# Generated by Django 3.0.8 on 2020-07-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumo',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='resumo',
            name='materia',
            field=models.CharField(choices=[('Mat', 'Matemática'), ('Qui', 'Química'), ('Mat', 'Física'), ('Mat', 'biologia'), ('Mat', 'História'), ('Mat', 'Geografia'), ('Mat', 'Gramática'), ('Mat', 'Literatura'), ('Mat', 'Redação'), ('Mat', 'Filosofia'), ('Mat', 'Sociologia')], max_length=15),
        ),
    ]
