# Generated by Django 3.0.8 on 2020-07-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0002_auto_20200720_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumo',
            name='materia',
            field=models.CharField(choices=[('Mat', 'Matemática'), ('Qui', 'Química'), ('Fis', 'Física'), ('biologia', 'biologia'), ('Mat', 'História'), ('Mat', 'Geografia'), ('Mat', 'Gramática'), ('Mat', 'Literatura'), ('Mat', 'Redação'), ('Mat', 'Filosofia'), ('Mat', 'Sociologia')], max_length=15),
        ),
    ]
