# Generated by Django 3.0.8 on 2020-07-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0003_auto_20200720_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumo',
            name='materia',
            field=models.CharField(choices=[('matematica', 'Matemática'), ('quimica', 'Química'), ('fisica', 'Física'), ('biologia', 'Biologia'), ('historia', 'História'), ('geografia', 'Geografia'), ('gramatica', 'Gramática'), ('literatura', 'Literatura'), ('redacao', 'Redação'), ('filosofia', 'Filosofia'), ('sociologia', 'Sociologia')], max_length=15),
        ),
    ]
