# Generated by Django 3.0.8 on 2020-07-21 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0002_questoes_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='questoes',
            name='numero',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(1)]),
        ),
    ]
